pub mod activation_functions;
pub mod node_kind;
pub mod network_definition;
pub mod network_definition_node_layer_resolver;
pub type NodePosition = (types::NeatFloat,types::NeatFloat,types::NeatFloat);
pub mod random;
pub mod types;
pub use types::NeatFloat as NeatFloat;
pub mod event_stream;
pub mod cpu_limiter;